better error handling

diff --git a/scripts/publish-sentry-release b/scripts/publish-sentry-release
--- a/scripts/publish-sentry-release
+++ b/scripts/publish-sentry-release
@@ -1,5 +1,7 @@
 #!/bin/sh
 
+set -e
+
 require_clean_work_tree () {
   # Update the index
   git update-index -q --ignore-submodules --refresh
@@ -59,7 +61,7 @@ upload_release_to_sentry () {
 
   local releaseStatusCode=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "https://app.getsentry.com/api/0/projects/$SENTRY_TEAM/$SENTRY_PROJECT/releases/$RELEASE_ID/")
 
-  if [ releaseStatusCode != '404' ]; then;
+  if [ "$releaseStatusCode" != "404" ]; then
     echo "Delete existing Sentry release?"
     select yn in "Yes" "No"; do
       case $yn in
@@ -108,17 +110,17 @@ upload_release_to_sentry () {
 
 create_release () {
   if [ "$SENTRY_API_KEY" == "" ]; then
-    echo "Must specify Sentry API Key."
+    echo >&2 "Must specify Sentry API Key."
     exit 1;
   fi
 
   if [ "$PLATFORM" != 'ios' ] && [ "$PLATFORM" != 'android' ]; then
-    echo "Platform must be specified ('ios' or 'android')."
+    echo >&2 "Platform must be specified ('ios' or 'android')."
     exit 1;
   fi
 
   if [ "$SENTRY_TEAM" == "" ] || [ "$SENTRY_PROJECT" == "" ]; then
-    echo "Must specify the Sentry team and project."
+    echo >&2 "Must specify the Sentry team and project."
     exit 1;
   fi
 
@@ -131,7 +133,7 @@ create_release () {
   read XDE_PORT
 
   if [ "$XDE_PORT" == "" ]; then
-    echo "Must enter a port."
+    echo >&2 "Must enter a port."
     exit 1
   fi
 
@@ -153,18 +155,30 @@ create_release () {
   mkdir -p "./.release/$PLATFORM"
 
   echo "\nFetching build from XDE...(may take a while, due to minify)"
-  curl "http://localhost:$XDE_PORT/bundle?dev=false&minify=true" \
-    -k \
-    --progress-bar \
-    -o "./.release/$PLATFORM/bundle" \
-    -H "exponent-platform: $PLATFORM" > /dev/null
+  {
+    curl "http://localhost:$XDE_PORT/bundle?dev=false&minify=true" \
+      -k \
+      -f \
+      --progress-bar \
+      -o "./.release/$PLATFORM/bundle" \
+      -H "exponent-platform: $PLATFORM" 1> /dev/null
+  } || {
+    echo >&2 "\n\033[0;31mError fetching build from XDE. Please check your XDE port and that XDE is running."
+    exit 1
+  }
 
   echo "\nFetching source map from XDE..."
-  curl "http://localhost:$XDE_PORT/map" \
-    -k \
-    --progress-bar \
-    -o "./.release/$PLATFORM/map" \
-    -H "exponent-platform: $PLATFORM" > /dev/null
+  {
+    curl "http://localhost:$XDE_PORT/map" \
+      -k \
+      -f \
+      --progress-bar \
+      -o "./.release/$PLATFORM/map" \
+      -H "exponent-platform: $PLATFORM" 1> /dev/null
+  } || {
+    echo >&2 "\n\033[0;31mError fetching source map from XDE. Please check your XDE port and that XDE is running."
+    exit 1
+  }
 
   echo "\nModifying bundle and source map..."
 
@@ -220,3 +234,4 @@ while [ "$1" != "" ]; do
 done
 
 create_release
+
